name: Weekly AWS Security Scan

on:
  schedule:
    - cron: '0 2 * * 0'   # Runs every Sunday at 2am UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install boto3

    - name: Run AWS Security Scanner
      run: python aws_security_scanner.py

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: reports/security_report.txt